"""
Script to download the Roboflow Aerial Airplane Detection model.
"""
import os
import sys

MODELS_DIR = os.path.join(os.path.dirname(__file__), "models")
os.makedirs(MODELS_DIR, exist_ok=True)

print("=" * 70)
print("Roboflow Aerial Airplane Detection Model Downloader")
print("=" * 70)
print()
print("You found the perfect model!")
print("URL: https://universe.roboflow.com/aerial-airplane-detection/model/1")
print()
print("This model is trained on aerial imagery and should work much better!")
print()
print("=" * 70)
print("DOWNLOAD INSTRUCTIONS:")
print("=" * 70)
print()
print("Method 1 - Manual Download (Easiest):")
print("  1. Go to the Roboflow page in your browser")
print("  2. Click on 'Model' in the left sidebar")
print("  3. Click 'Download Model'")
print("  4. Select format: 'YOLOv8'")
print("  5. Download the .pt file")
print("  6. Copy the downloaded file to:")
print(f"     {MODELS_DIR}")
print()
print("Method 2 - Using Roboflow Python Package:")
print("  1. Install roboflow: pip install roboflow")
print("  2. Run this code:")
print("     from roboflow import Roboflow")
print("     rf = Roboflow(api_key='YOUR_API_KEY')")
print("     project = rf.workspace().project('aerial-airplane-detection')")
print("     model = project.version(1).model")
print("     model.download('yolov8', location='models/')")
print()
print("Method 3 - Direct Download (if available):")
print("  Some models allow direct download. Check the 'Model' tab for a direct link.")
print()
print("=" * 70)
print("AFTER DOWNLOADING:")
print("=" * 70)
print()
print("1. Refresh the Streamlit app")
print("2. Select the new model from the 'YOLOv8 Weights' dropdown")
print("3. Try detection again!")
print()
print("Current models in your folder:")
for f in sorted(os.listdir(MODELS_DIR)):
    if f.endswith('.pt'):
        size = os.path.getsize(os.path.join(MODELS_DIR, f)) / (1024*1024)
        print(f"  - {f} ({size:.2f} MB)")
print()
